name: emotion_sense_mobile_app
description: Help in recognizing emotions for people with autistic spectrum disorder.

publish_to: 'github.com/pchkauu'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  auto_route: ^7.8.4
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  lottie: ^2.7.0
  permission_handler: ^11.0.1
  sprung: ^3.0.1
  tflite_v2: ^1.0.0
  wakelock_plus: ^1.1.3
  wtf_sliding_sheet: ^1.1.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  # flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/android/play_store_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/locale/
    - assets/ai_model/
    - assets/app_icon/
    - assets/ui_kit/emotion/
    - assets/ui_kit/emotion_id/
    - assets/ui_kit/navigation/
    - assets/ui_kit/lottie/
    - assets/fonts/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
